behaviors:
  IntersectionControl:
    trainer_type: ppo
    hyperparameters:
      batch_size: 100
      buffer_size: 5000
      learning_rate: 3.0e-4
      beta: 5.0e-3
      epsilon: 0.2
      lambd: 0.93
      num_epoch: 5
      learning_rate_schedule: linear
    network_settings:
      normalize: false
      hidden_units: 128
      num_layers: 2
    reward_signals:
      extrinsic:
        gamma: 0.92
        strength: 1.0
    max_steps: 1500000
    time_horizon: 64
    summary_freq: 5000
